spring:
  datasource: 
    url: jdbc:mysql://database:3306/friend_management?useSSL=false
    username: fm_admin
    password: fm_admin_password
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
  servlet:
    context-path: /friend-management
    
logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    