spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/friend_management
    username: fm_admin
    password: fm_admin_password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect