spring:
  datasource: 
    url: jdbc:mysql://database:3306/friend_database
    username: friend_admin
    password: friend_admin_password
  jpa:
    show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect